# This file was generated by GoReleaser. DO NOT EDIT.
cask "solidtime" do
  version "0.2.2"

  on_macos do
    sha256 "d3455e4e20931646db053a30a2caac075ce7c08fbfe9c0fd14cff46138773be1"
    url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "db305a75629e0ba830166d1535822a9df3b89ac6f6d4ee0f0d75ee028e9b5d21"
      url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d711d6a89f5677fd195bba06a610d0a44d096379956a4bebd9b20f3fa4bfa869"
      url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "solidtime"
  desc "Report tracked hours and billable totals from solidtime"
  homepage "https://github.com/zeriaxdev/solidtime-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "solidtime"

  postflight do
    # The binary is not notarized, so Gatekeeper would quarantine it.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/solidtime"]
    end
  end

  # No zap stanza required

end
