# This file was generated by GoReleaser. DO NOT EDIT.
cask "solidtime" do
  version "0.2.0"

  on_macos do
    sha256 "7b1964c1d4909b74a95dfbbe6b9297840a1a4e921e8fddebfe8c4754522a73dc"
    url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "3a602af854dcbe0925036333071468300f7f14dab350e0196e5cb40231efa765"
      url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c49dfed90cb9190e16b28ea0c432ae7d8d14911c0e3fb509dc33fe6f459008c5"
      url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "solidtime"
  desc "Report tracked hours and billable totals from solidtime"
  homepage "https://github.com/zeriaxdev/solidtime-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "solidtime"

  postflight do
    # The binary is not notarized, so Gatekeeper would quarantine it.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/solidtime"]
    end
  end
  generate_completions_from_executable "solidtime", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
