# This file was generated by GoReleaser. DO NOT EDIT.
cask "solidtime" do
  version "0.5.0"

  on_macos do
    sha256 "7130ef4c6ba075ae1ada72cdcc129cbecadf2aae23677ea2ac50f0ca94f6afb1"
    url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "6d4b99aaa526379446052961344198105e48214e0aece10a459f60501386d51f"
      url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fb12db3c13eb14e7f32eecb03da79073ced1be107db1158ab463dabbd4cd53ab"
      url "https://github.com/zeriaxdev/solidtime-cli/releases/download/v#{version}/solidtime-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "solidtime"
  desc "Report tracked hours and billable totals from solidtime"
  homepage "https://github.com/zeriaxdev/solidtime-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "solidtime"

  postflight do
    # The binary is not notarized, so Gatekeeper would quarantine it.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/solidtime"]
    end
  end

  # No zap stanza required

end
